name: Local Testing for Mobile

on:
  push:
    branches:
      - 'branch-A'  # Trigger only when pushing to branch-A
  pull_request:
    branches:
      - 'staging_v2'  # Trigger on PR to staging_v2 (full CI pipeline)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          build-tools-version: '34.0.0'
          platform-version: '34'

      - name: Build with Gradle
        working-directory: Mobile
        run: ./gradlew build

      - name: Run mobile unit tests (local testing)
        working-directory: Mobile
        run: ./gradlew test