name: Local Testing for Frontend

on:
  push:
    branches:
      - 'branch-A'  # Trigger only when pushing to branch-A
  pull_request:
    branches:
      - 'staging_v2'  # Trigger on PR to staging_v2 (full CI pipeline)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Web/kebunjio/package-lock.json

      - name: Install dependencies
        working-directory: Web/kebunjio
        run: npm ci

      - name: Run React tests (local testing)
        working-directory: Web/kebunjio
        run: npm test -- --watchAll=false --ci