name: Local Testing for Backend

on:
  push:
    branches:
      - 'branch-A'  # Trigger only when pushing to branch-A
  pull_request:
    branches:
      - 'staging_v2'  # Trigger on PR to staging_v2 (full CI pipeline)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven (local testing)
        run: mvn test
        working-directory: Backend/KebunJio